# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetLinearKernel <- function(X) {
    .Call('_MAPITR_GetLinearKernel', PACKAGE = 'MAPITR', X)
}

MAPITRBase <- function(X, Y, regions, cores = 1L) {
    .Call('_MAPITR_MAPITRBase', PACKAGE = 'MAPITR', X, Y, regions, cores)
}

